export const assets = {
	icons: {
		raceCar: '/icons/race-car.svg',
		finishLine: '/icons/finish-line.svg',
		carIcon: '/icons/ion-car-sport.svg',
		between: '/icons/between.svg',
		google: '/icons/google-icon.svg',
		apple: '/icons/apple-icon.svg'
	},
	images: {
		bike: '/images/bike.png',
		car: '/images/car.png',
		logo: '/images/eagleLogo.png',
		home: '/images/home.png',
		health: '/images/Health.png',
		travel: '/images/travel.jpeg',
		boat: '/images/boat.jpeg',
		personal: '/images/personal.png',
		peugeotLogo: '/images/peugeot.png',
		coupe: '/images/coupe.png',
		hat: '/images/hat.png',
		mini: '/images/mini.png',
		sedan: '/images/sedan.png',
		suv: '/images/suv.png',
		truck: '/images/truck.png',
		vw: '/images/vw.png',
		audi: '/images/audi.png',
		bentley: '/images/bentley.png',
		benz: '/images/benz.png',
		bmw: '/images/BMW.png',
		ford: '/images/ford.png',
		jeep: '/images/jeep.png',
		nissan: '/images/nissan.png',
		trip: '/images/trip.jpeg',
		qr: '/images/qrcode.png',
		family: '/images/family.png',
		vehicleSketch: '/images/vehicleSketch.svg',
		sClass: '/images/SClass.png',
		person: '/images/person.jpeg'
	}
}
